services:
  postgres:
    image: postgres:18
    container_name: transi-store-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-transistore}
      POSTGRES_USER: ${DB_USER:-transistore}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-transistore}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transi-store-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-transistore} -d ${DB_DATABASE:-transistore}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: transi-store-app
    build:
      context: .
      dockerfile: ./Dockerfile
      # network: host
    networks:
      - transi-store-network
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: no # unless-stopped mais bug et restart en boucle
    ports:
      - "${APP_PORT:-5173}:5173"
      - "${APP_PORT_PROD:-3000}:3000" # Pour le start en prod
    volumes:
      - .:/app
      # Volume anonyme pour node_modules : empêche l'écrasement par le bind mount Windows
      - /app/node_modules
      # Volume anonyme pour .yarn/cache pour éviter les problèmes de permissions
      - /app/.yarn/cache

volumes:
  postgres_data:

networks:
  transi-store-network:
    driver: bridge
    name: transi-store-network
    driver_opts:
      com.docker.network.bridge.name: transi-store-network
      com.docker.network.bridge.host_binding_ipv4: 0.0.0.0
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.driver.mtu: 1500