services:
  postgres:
    image: postgres:18
    container_name: transi-store-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-transistore}
      POSTGRES_USER: ${DB_USER:-transistore}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-transistore}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-transistore} -d ${DB_DATABASE:-transistore}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: transi-store-app
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "${APP_PORT:-5173}:5173"
    volumes:
      - .:/app
      # Volume anonyme pour node_modules : empêche l'écrasement par le bind mount Windows
      - /app/node_modules
      # Volume anonyme pour .yarn/cache pour éviter les problèmes de permissions
      - /app/.yarn/cache

volumes:
  postgres_data:
