name: CI

on:
  push:
    branches: [main]
  pull_request: ~

permissions:
  contents: read

jobs:
  typecheck:
    name: TypeScript Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init repository dependencies
        uses: ./.github/actions/setup-project

      - name: Run lint:types
        run: yarn lint:types

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init repository dependencies
        uses: ./.github/actions/setup-project

      - name: Run lint:eslint
        run: yarn lint:eslint

  knip:
    name: Knip Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init repository dependencies
        uses: ./.github/actions/setup-project

      - name: Run knip
        run: yarn knip

  i18next:
    name: i18next Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init repository dependencies
        uses: ./.github/actions/setup-project

      - name: Run i18next
        run: yarn i18next-cli lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init repository dependencies
        uses: ./.github/actions/setup-project

      - name: Run i18next
        run: yarn test
